[workspace]
resolver = "2"
members = ["crates/db", "crates/gate", "crates/jwt", "crates/lb", "crates/store", "crates/oauth", "crates/pw", "crates/smtp",
    "crates/stargate", "crates/ace", "crates/tools"]

[workspace.package]
version = "0.1.0"
authors = [
    "Alessio Forte <fortealessio@gmail.com>",
]
description = "Stargate API Gateway and IAM"
readme = "README.md"
edition = "2024"
license = "MIT"

[profile.dev]
debug = 1

[profile.dev.package."*"]
debug = false
opt-level = 2
