[workspace]
resolver = "2"
members = [ "crates/gate", "crates/jwt", "crates/oauth", "crates/password", "crates/smtp",
    "crates/stargate"
]

[workspace.package]
version = "0.1.0"
authors = [
    "Alessio Forte <fortealessio@gmail.com>",
]
description = "Stargate API Gateway and IAM"
readme = "README.md"
edition = "2021"
license = "MIT"
