[package]
name = "stargate"
version.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"

[package.metadata.release]
tag-message = "chore: :bookmark: Release `{{crate_name}}` version {{version}}"
publish = false
push = false

[dependencies]
actix-cors = "0.7.1"
actix-governor = "0.8.0"
actix-session = { version = "0.10.0", features = ["cookie-session"] }
actix-web = { version = "4.11.0", features = ["openssl"] }
actix-web-grants = "4.1.2"
actix-web-httpauth = "0.8.2"
actix-ws-proxy = "0.1.2"
awc = { version = "3.7.0", features = ["openssl"] }
db = { path = "../db" }
chrono = "0.4.41"
dotenvy = "0.15.7"
gate = { path = "../gate" }
jwt = { path = "../jwt" }
lb = { path = "../lb" }
log = "0.4.27"
mime = "0.3.17"
oauth = { path = "../oauth" }
openssl = "0.10.72"
password = { path = "../password" }
pretty_env_logger = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yml = "0.0.12"
smtp = { path = "../smtp" }
thiserror = "2.0.12"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
utoipa = { version = "5.3.1", features = ["actix_extras", "yaml"] }
uuid = { version = "1.16.0", features = ["v4"] }
once_cell = "1.21.3"
