{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stargate-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/alessioforte/.pv-kubernetes
{{- end }}
