{{- if .Values.runtimeSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stargate.runtimeSecretName" . }}
  labels:
    {{- include "stargate.labels" . | nindent 4 }}
  {{- with .Values.runtimeSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.runtimeSecret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
