apiVersion: v2
name: stargate
description: Stargate IAM server and API gateway
type: application
version: 0.2.0
appVersion: "0.1.0"
kubeVersion: ">=1.25.0-0"
home: https://github.com/alessioforte/stargate
sources:
  - https://github.com/alessioforte/stargate
icon: https://raw.githubusercontent.com/alessioforte/stargate/main/apps/auth/public/favicon.svg
keywords:
  - iam
  - oauth
  - oidc
  - api-gateway
