[package]
name = "lb"
version.workspace = true
authors.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ahash = "0.8"
async-trait = "0.1.89"
chrono = "0.4.44"
dashmap = "6.1.0"
rand = "0.10.0"
reqwest = "0.13.2"
tokio = "1.51.1"
tracing = "0.1.44"
